kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0ecc708bd4f79e28c
  directoryPerms: "700"
  basepath: "/roboshop"